services:
  stend-api:
    build:
      context: .
    image: stend-api
    environment:
      # Taille maximale autorisée par fichier en octets (par défaut: 1000000000 / 1 Go)
      FILE_MAX_SIZE: 1000000000

      # Mot de passe requis avant d'envoyer un fichier
      # Si l'option est vide, aucune information ne sera demandé aux utilisateurs et l'instance ne sera pas protégé
      # Le téléchargement d'un fichier ne demandera jamais ce mot de passe, même si l'option est définie
      API_PASSWORD: password

      # Durée maximale avant qu'un fichier n'expire et ne soit supprimé définitivement (par défaut: 2592000 / 30 jours)
      # Durées recommendées :
      # 1800 = 30 minutes
      # 21600 = 6 heures
      # 43200 = 12 heures
      # 86400 = 1 jour
      # 345600 = 4 jours
      # 604800 = 1 semaine
      # 1209600 = 2 semaine
      # 2592000 = 1 mois
      # 7776000 = 3 mois
      # 15552000 = 6 mois
      # 0 = Ne jamais expirer
      FILE_MAX_AGE: 2592000

      # Port sur lequel l'API écoutera
      PORT: 3000

      # Le serveur est-il derrière un reverse proxy ?
      # Cette valeur est importante, puisqu'une personne malveillante pourrait abuser d'une mauvaise configuration afin de se faire passer pour une autre personne
      # Si "true", l'API utilisera l'header X-Forwarded-For pour récupérer l'adresse IP du client
      # Si "cloudflare", l'API utilisera l'header CF-Connecting-IP pour récupérer l'adresse IP du client
      # Si "false", l'API utilisera l'adresse IP du dernier client contacté
      USING_REVERSE_PROXY: true

      # Taille d'un chunk en octets (par défaut: 20000000 / 20 Mo)
      # Note: assurez-vous que votre configuration (nginx, apache, ...) autorise les requêtes de cette taille
      # Dans le cas contraire, une erreur 413 (Payload Too Large) sera retournée lors de requêtes d'un chunk complet à l'API
      # https://stackoverflow.com/a/37916740/16155654
      CHUNK_SIZE: 20000000

      # Marge lors de la vérification de l'espace disponible sur le disque en octets (par défaut: 100000000 / 100 Mo)
      # Si l'espace sur le disque est inférieur à la taille du fichier + cette marge, l'API refusera de stocker le fichier
      # Sur un environnement où le disque est réservé à Stend, il est recommandé de définir une valeur assez basse (ex: 1000000 / 1 Mo)
      DISK_SPACE_MARGIN: 100000000

      # Chemin où seront stockés les fichiers dans le conteneur (doit être accessible en écriture, contiendra les données utilisateurs)
      # Si ce volume est supprimé, toutes les données utilisateurs seront perdues
      # Dans le cas où cette variable est modifiée, il est nécessaire de modifier le volume correspondant
      STORAGE_PATH: /usr/src/app/stend_storage
    ports:
      - 3000:3000
    volumes:
      - stend_storage:/usr/src/app/stend_storage

volumes:
  stend_storage:
